Models/ESSEmployee/EBank.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudIntern.Models.ESSEmployee;

public partial class EBank
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Bank name is required.")]
    public string? Name { get; set; }

    [Required(ErrorMessage = "Bank value is required.")]
    public string? Value { get; set; }
}

Models/ESSEmployee/ECity.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudIntern.Models.ESSEmployee;

public partial class ECity
{
    public int Id { get; set; }

    [Required(ErrorMessage = "City name is required.")]
    public string? Name { get; set; }

    [Required(ErrorMessage = "Value is required.")]
    public string? Value { get; set; }

    [Required(ErrorMessage = "ProvinceId is required.")]
    public int? ProvinceId { get; set; }

    public virtual EProvince? Province { get; set; }
}

Models/ESSEmployee/ECostCenter.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudIntern.Models.ESSEmployee;

public partial class ECostCenter
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Name is required.")]
    public string? Name { get; set; }

    [Required(ErrorMessage = "Code is required.")]
    public string? Code { get; set; }

    [Required(ErrorMessage = "CostCenter is required.")]
    public string? CostCenter { get; set; }
}

Models/ESSEmployee/ECountry.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudIntern.Models.ESSEmployee;

public partial class ECountry
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Name is required.")]
    public string? Name { get; set; }

    [Required(ErrorMessage = "Value is required.")]
    public string? Value { get; set; }

    [Required(ErrorMessage = "IsoCode is required.")]
    public string? IsoCode { get; set; }

    public virtual ICollection<EProvince> EProvinces { get; set; } = new List<EProvince>();
}

Models/ESSEmployee/EDepartment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudIntern.Models.ESSEmployee;

public partial class EDepartment
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Name is required.")]
    public string? Name { get; set; }

    [Required(ErrorMessage = "Value is required.")]
    public string? Value { get; set; }

    [Required(ErrorMessage = "Code is required.")]
    public string? Code { get; set; }

    public virtual ICollection<ESection> ESections { get; set; } = new List<ESection>();
}

Models/ESSEmployee/EEducation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudIntern.Models.ESSEmployee;

public partial class EEducation
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Name is required.")]
    public string? Name { get; set; }

    [Required(ErrorMessage = "Value is required.")]
    public string? Value { get; set; }
}

Models/ESSEmployee/EEmployeeStatus.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudIntern.Models.ESSEmployee;

public partial class EEmployeeStatus
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Name is required.")]
    public string? Name { get; set; }
    
    [Required(ErrorMessage = "Value is required.")]
    public string? Value { get; set; }
}

Models/ESSEmployee/EGrade.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudIntern.Models.ESSEmployee;

public partial class EGrade
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Name is required.")]
    public string? Name { get; set; }

    [Required(ErrorMessage = "Value is required.")]
    public string? Value { get; set; }
}

Models/ESSEmployee/EGradeCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudIntern.Models.ESSEmployee;

public partial class EGradeCategory
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Name is required.")]
    public string? Name { get; set; }

    [Required(ErrorMessage = "Value is required.")]
    public string? Value { get; set; }
}

Models/ESSEmployee/EHardshipLocation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudIntern.Models.ESSEmployee;

public partial class EHardshipLocation
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Name is required.")]
    public string? Name { get; set; }

    [Required(ErrorMessage = "Province is required.")]
    public string? Province { get; set; }

    [Required(ErrorMessage = "ProvinceId is required.")]
    public int? ProvinceId { get; set; }
}

Models/ESSEmployee/EInsurance.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudIntern.Models.ESSEmployee;

public partial class EInsurance
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Insurance name is required.")]
    public string? Name { get; set; }

    [Required(ErrorMessage = "Insurance value is required.")]
    public string? Value { get; set; }
}

Models/ESSEmployee/EMaritalStatus.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudIntern.Models.ESSEmployee;

public partial class EMaritalStatus
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Name is required.")]
    public string? Name { get; set; }

    [Required(ErrorMessage = "Value is required.")]
    public string? Value { get; set; }
}

Models/ESSEmployee/ENationality.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudIntern.Models.ESSEmployee;

public partial class ENationality
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Name is required.")]
    public string? Name { get; set; }

    [Required(ErrorMessage = "Value is required.")]
    public string? Value { get; set; }
}

Models/ESSEmployee/EOccupation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudIntern.Models.ESSEmployee;

public partial class EOccupation
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Name is required.")]
    public string? Name { get; set; }

    [Required(ErrorMessage = "Value is required.")]
    public string? Value { get; set; }
}

Models/ESSEmployee/EPosition.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudIntern.Models.ESSEmployee;

public partial class EPosition
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Name is required.")]
    public string? Name { get; set; }

    [Required(ErrorMessage = "Value is required.")]
    public string? Value { get; set; }

    public string? Authorization { get; set; }
}

Models/ESSEmployee/EProvince.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudIntern.Models.ESSEmployee;

public partial class EProvince
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Name is required.")]
    public string? Name { get; set; }

    [Required(ErrorMessage = "Value is required.")]
    public string? Value { get; set; }

    [Required(ErrorMessage = "CountryId is required.")]
    public int? CountryId { get; set; }

    public virtual ECountry? Country { get; set; }

    public virtual ICollection<ECity> ECities { get; set; } = new List<ECity>();
}

Models/ESSEmployee/ERelationship.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudIntern.Models.ESSEmployee;

public partial class ERelationship
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Name is required.")]
    public string? Name { get; set; }

    [Required(ErrorMessage = "Value is required.")]
    public string? Value { get; set; }
}

Models/ESSEmployee/EReligion.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudIntern.Models.ESSEmployee;

public partial class EReligion
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Name is required.")]
    public string? Name { get; set; }

    [Required(ErrorMessage = "Value is required.")]
    public string? Value { get; set; }
}

Models/ESSEmployee/ESection.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudIntern.Models.ESSEmployee;

public partial class ESection
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Name is required.")]
    public string? Name { get; set; }

    [Required(ErrorMessage = "Value is required.")]
    public string? Value { get; set; }

    [Required(ErrorMessage = "DepartmentId is required.")]
    public int? DepartmentId { get; set; }

    [Required(ErrorMessage = "Code is required.")]
    public string? Code { get; set; }

    public virtual EDepartment? Department { get; set; }
}

Models/ESSEmployee/ESectionController.cs
using CrudIntern.Services;
using Microsoft.AspNetCore.Mvc;

namespace CrudIntern.Models.ESSEmployee
{
    public class ESectionController : Controller
    {
        private readonly MyAppDbContext context;

        public ESectionController(MyAppDbContext context)
        {
            this.context = context;
        }
        public IActionResult Index(string searchTerm)
        {
            ViewData["CurrentFilter"] = searchTerm;
            var Section = from c in context.ESections
                             select new ESection
                             {
                                 Id = c.Id,
                                 Name = c.Name ?? "N/A",
                                 Value = c.Value ?? "N/A",
                                 DepartmentId = c.DepartmentId ?? 0,
                                 Code = c.Code ?? "N/A"
                             };
            if (!string.IsNullOrEmpty(searchTerm))
            {
                Section = Section.Where(b => b.Name.Contains(searchTerm));
            }
            return View("~/Views/ESSEmployee/ESection/Index.cshtml", Section.ToList());
        }

        [HttpPost]
        public IActionResult Create(ESection newSection)
        {
            if (context.ESections.Any(b => b.Name.ToLower() == newSection.Name.ToLower()))
            {
                return Json(new { success = false, message = "This Section already exists." });
            }
            context.ESections.Add(newSection);
            context.SaveChanges();

            return Json(new { success = true });
        }

        [HttpPost]
        public IActionResult Edit(ESection updatedSection)
        {
            var existingSection = context.ESections.Find(updatedSection.Id);

            if (existingSection == null)
            {
                return NotFound();
            }
            bool nameExists = context.ESections
                .Any(b => b.Name.ToLower() == updatedSection.Name.ToLower() && b.Id != updatedSection.Id);

            if (nameExists)
            {
                return Json(new { success = false, message = "This Section already exists." });
            }

            existingSection.Name = updatedSection.Name ?? existingSection.Name;
            existingSection.Value = updatedSection.Value ?? existingSection.Value;
            existingSection.DepartmentId = updatedSection.DepartmentId ?? existingSection.DepartmentId;
            existingSection.Code = updatedSection.Code ?? existingSection.Code;

            context.SaveChanges();

            return Json(new { success = true });
        }
    }
}

Views/ESSEmployee/ESection/Index.cshtml
@using CrudIntern.Models.ESSEmployee
@model List<ESection>
@{
}

<h2 class="text-center mb-5">List Section</h2>
<div class="row mb-5">
    <div class="col-md-6">
        <!-- Search Bar -->
        <div class="input-group">
            <input type="text" id="searchSection" class="form-control" placeholder="Search by Section name...">
            <div class="input-group-append">
                <span class="input-group-text">
                    <i class="fas fa-search"></i>
                </span>
            </div>
        </div>
    </div>
    <div class="col-md-6 text-right">
        <!-- Create Button -->
        <button id="openCreateModal" class="btn btn-success" data-toggle="modal" data-target="#createModal">
            <i class="fas fa-plus"></i> New Section
        </button>
    </div>
</div>
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Section List</h3>
    </div>
    <div class="card-body">
        @if (ViewData["ErrorMessage"] != null)
        {
            <div class="alert alert-danger">
                @ViewData["ErrorMessage"]
            </div>
        }
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Value</th>
                    <th>DepartmentId</th>
                    <th>Code</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var Section in Model)
                {
                    <tr>
                        <td>@Section.Id</td>
                        <td>@(Section.Name ?? "N/A")</td>
                        <td>@(Section.Value ?? "N/A")</td>
                        <td>@(Section.DepartmentId.HasValue ? Section.DepartmentId.ToString() : "N/A")</td>
                        <td>@(Section.Code ?? "N/A")</td>
                        <td>
                            <button class="btn btn-primary btn-sm" onclick="openEditModal('@Section.Id', '@(Section.Name ?? "N/A")', '@(Section.Value ?? "N/A")', '@(Section.DepartmentId.HasValue ? Section.DepartmentId.ToString() : "N/A")', '@(Section.Code ?? "N/A")')">
                                <i class="fas fa-edit"></i> Edit
                            </button>
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>

<!-- Create Modal -->
<div id="createModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Create New Section</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="createSectionForm" method="post" asp-controller="ESection" asp-action="Create">
                    <div class="form-group">
                        <label for="Name">Section Name</label>
                        <input type="text" class="form-control" id="Name" name="Name" required />
                    </div>
                    <div class="form-group">
                        <label for="Value">Value</label>
                        <input type="text" class="form-control" id="Value" name="Value" required />
                    </div>
                    <div class="form-group">
                        <label for="Value">DepartmentId</label>
                        <input type="text" class="form-control" id="Value" name="Value" required />
                    </div>
                    <div class="form-group">
                        <label for="Section">Code</label>
                        <input type="text" class="form-control" id="Code" name="Code" required />
                    </div>
                    <button type="submit" class="btn btn-success">Create</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Edit Modal -->
<div id="editModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit Section</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="editErrorAlert" class="alert alert-danger" style="display: none;"></div>

                <form id="editSectionForm" method="post" asp-controller="ESection" asp-action="Edit">
                    <input type="hidden" id="editSectionId" name="Id" />
                    <div class="form-group">
                        <label for="editName">Section Name</label>
                        <input type="text" class="form-control" id="editName" name="Name" required />
                    </div>
                    <div class="form-group">
                        <label for="editValue">Section Value</label>
                        <input type="text" class="form-control" id="editValue" name="Value" required />
                    </div>
                    <div class="form-group">
                        <label for="editDepartmentId">DepartmentId</label>
                        <input type="text" class="form-control" id="editDepartmentId" name="DepartmentId" required />
                    </div>

                    <div class="form-group">
                        <label for="editSection">Code</label>
                        <input type="text" class="form-control" id="editCode" name="Code" required />
                    </div>
                    <button type="submit" class="btn btn-success">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- jQuery Validation -->
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<!-- Bootstrap and jQuery -->
<link rel="stylesheet" href="~/css/bootstrap.min.css">
<script src="~/plugins/jquery/jquery.min.js"></script>
<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- SweetAlert -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>

<!-- Custom JavaScript -->
<script>
    function openEditModal(id, name, value, departmentId, code) {
        $('#editSectionId').val(id);
        $('#editName').val(name);
        $('#editValue').val(value);
        $('#editDepartmentId').val(departmentId);
        $('#editCode').val(code);

        $('#editModal').modal('show');
    }

</script>

<script>
    $(document).ready(function () {
        $('#searchSection').on('keyup', function () {
            var value = $(this).val().toLowerCase();
            $('.table tbody tr').filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });

    $(document).ready(function () {
        $('#createSectionForm').on('submit', function (event) {
            event.preventDefault();

            $.ajax({
                type: 'POST',
                url: $(this).attr('action'),
                data: $(this).serialize(),
                success: function (response) {
                    if (response.success) {
                        swal("Success!", "Section created successfully!", "success").then(() => {
                            $('#createModal').modal('hide');
                            location.reload();
                        });
                    } else {
                        swal("Error!", response.message, "error");
                    }
                },
                error: function (xhr, status, error) {
                    swal("Error!", "An error occurred. Please try again.", "error");
                }
            });
        });

        $('#editSectionForm').on('submit', function (event) {
            event.preventDefault();

            $.ajax({
                type: 'POST',
                url: $(this).attr('action'),
                data: $(this).serialize(),
                success: function (response) {
                    if (response.success) {
                        swal("Success!", "Section updated successfully!", "success").then(() => {
                            $('#editModal').modal('hide');
                            location.reload();
                        });
                    } else {
                        swal("Error!", response.message, "error");
                    }
                },
                error: function (xhr, status, error) {
                    swal("Error!", "An error occurred. Please try again.", "error");
                }
            });
        });
    });
</script>