Models/ESSFinance/MAttnCustomer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudIntern.Models.ESSFinance;

public partial class MAttnCustomer
{
    public int Id { get; set; }

    [Required(ErrorMessage = "BpCode is required.")]
    public string? BpCode { get; set; }

    [Required(ErrorMessage = "AttnName is required.")]
    public string? AttnName { get; set; }

    [Required(ErrorMessage = "Email is required.")]
    public string? Email { get; set; }

    [Required(ErrorMessage = "Description is required.")]
    public string? Description { get; set; }
}

Models/ESSFinance/MBankingRoutingCode.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudIntern.Models.ESSFinance;

public partial class MBankingRoutingCode
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Bank Name is required.")]
    public string? BankName { get; set; }

    [Required(ErrorMessage = "Bank Code is required.")]
    public string? RoutingCode { get; set; }
}

Models/ESSFinance/MBenefitGradeConfig.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CrudIntern.Models.ESSFinance;

public partial class MBenefitGradeConfig
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Grade is required.")]
    public string? Grade { get; set; }

    [Required(ErrorMessage = "Optical Frame value is required.")]
    public int? OpticalFrame { get; set; }

    [Required(ErrorMessage = "Optical Lense value is required.")]
    public int? OpticalLense { get; set; }

    [Required(ErrorMessage = "Medical value is required.")]
    public int? Medical { get; set; }

    [Required(ErrorMessage = "Pointing value is required.")]
    public int? Pointing { get; set; }

    [Required(ErrorMessage = "Loan value is required.")]
    public int? Loan { get; set; }

    [Required(ErrorMessage = "RA value is required.")]
    public int? Ra { get; set; }

    [Required(ErrorMessage = "Overtime status is required.")]
    public bool? IsOvertime { get; set; }

    [Required(ErrorMessage = "Config Type is required.")]
    public string? ConfigType { get; set; }

    [Required(ErrorMessage = "COP value is required.")]
    public int? Cop { get; set; }

    [Required(ErrorMessage = "Car Loan value is required.")]
    public int? CarLoan { get; set; }

    [Required(ErrorMessage = "Home Renovation value is required.")]
    public int? HomeRenov { get; set; }

    [Required(ErrorMessage = "Emergency Loan value is required.")]
    public int? EmergencyLoan { get; set; }
}

Models/ESSFinance/MConfigApprovalGeneralInformation.cs
using System;
using System.Collections.Generic;

namespace CrudIntern.Models.ESSFinance;

public partial class MConfigApprovalGeneralInformation
{
    public int Id { get; set; }

    public int? DepartmentId { get; set; }

    public string? DepartmentName { get; set; }

    public string? ApprovalType { get; set; }

    public string? Nrp { get; set; }

    public string? Name { get; set; }
}

Models/ESSFinance/MConfigApprovalVendorCriterion.cs
using System;
using System.Collections.Generic;

namespace CrudIntern.Models.ESSFinance;

public partial class MConfigApprovalVendorCriterion
{
    public int Id { get; set; }

    public int? DepartmentId { get; set; }

    public string? DepartmentName { get; set; }

    public string? ApprovalType { get; set; }

    public string? Nrp { get; set; }

    public string? Name { get; set; }
}

Models/ESSFinance/MCustomer.cs
using System;
using System.Collections.Generic;

namespace CrudIntern.Models.ESSFinance;

public partial class MCustomer
{
    public int Id { get; set; }

    public string? SettlementAccount { get; set; }

    public string? CustomerReferenceBaanwf { get; set; }

    public string? CustomerReference { get; set; }

    public string? BeneFiciaryName { get; set; }

    public string? BeneFiciaryAddress { get; set; }

    public string? BeneFiciaryAccount { get; set; }

    public string? RemittingCurrency { get; set; }

    public string? PaymentType { get; set; }

    public string? BeneficiaryBank { get; set; }

    public string? BankCountry { get; set; }

    public string? BankCode { get; set; }

    public string? Resident { get; set; }

    public string? BeneficiaryType { get; set; }

    public string? AccountNum { get; set; }

    public string? BpCode { get; set; }

    public string? Email { get; set; }

    public string? CustomerType { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public string? Clasify { get; set; }

    public string? Location { get; set; }

    public string? Type { get; set; }

    public string? Nrp { get; set; }

    public string? Phone { get; set; }

    public string? City { get; set; }

    public string? Country { get; set; }

    public string? PostalCode { get; set; }

    public string? MarketingPhone { get; set; }

    public string? MarketingEmail { get; set; }

    public string? BillingPhone { get; set; }

    public string? BillingEmail { get; set; }

    public string? TaxesPhone { get; set; }

    public string? TaxesEmail { get; set; }

    public string? PengusahaKenaPajak { get; set; }

    public string? NpwpNumber { get; set; }

    public int? TermOfPayment { get; set; }

    public string? TransactionType { get; set; }

    public string? TableConnectId { get; set; }

    public string? TempSettlementAccount { get; set; }

    public string? TempCustomerReferenceBaanwf { get; set; }

    public string? TempCustomerReference { get; set; }

    public string? TempBeneFiciaryName { get; set; }

    public string? TempBeneFiciaryAddress { get; set; }

    public string? TempBeneFiciaryAccount { get; set; }

    public string? TempRemittingCurrency { get; set; }

    public string? TempPaymentType { get; set; }

    public string? TempBeneficiaryBank { get; set; }

    public string? TempBankCountry { get; set; }

    public string? TempBankCode { get; set; }

    public string? TempResident { get; set; }

    public string? TempBeneficiaryType { get; set; }

    public string? TempAccountNum { get; set; }

    public string? TempBpCode { get; set; }

    public string? TempEmail { get; set; }

    public string? TempCustomerType { get; set; }

    public DateTime? TempCreatedAt { get; set; }

    public DateTime? TempUpdateAt { get; set; }

    public string? TempClasify { get; set; }

    public string? TempLocation { get; set; }

    public string? TempPhone { get; set; }

    public string? TempCity { get; set; }

    public string? TempCountry { get; set; }

    public string? TempPostalCode { get; set; }

    public string? TempMarketingPhone { get; set; }

    public string? TempMarketingEmail { get; set; }

    public string? TempBillingPhone { get; set; }

    public string? TempBillingEmail { get; set; }

    public string? TempTaxesPhone { get; set; }

    public string? TempTaxesEmail { get; set; }

    public string? TempPengusahaKenaPajak { get; set; }

    public string? TempNpwpNumber { get; set; }

    public int? TempTermOfPayment { get; set; }

    public string? TempTransactionType { get; set; }

    public string? TempTableConnectId { get; set; }

    public string? Status { get; set; }

    public string? App1 { get; set; }

    public string? AppName1 { get; set; }

    public DateTime? AppDate1 { get; set; }

    public string? AppStatus1 { get; set; }

    public string? RejectReason1 { get; set; }

    public string? App2 { get; set; }

    public string? AppName2 { get; set; }

    public DateTime? AppDate2 { get; set; }

    public string? AppStatus2 { get; set; }

    public string? RejectReason2 { get; set; }

    public string? App3 { get; set; }

    public string? AppName3 { get; set; }

    public DateTime? AppDate3 { get; set; }

    public string? AppStatus3 { get; set; }

    public string? RejectReason3 { get; set; }

    public string? App4 { get; set; }

    public string? AppName4 { get; set; }

    public DateTime? AppDate4 { get; set; }

    public string? AppStatus4 { get; set; }

    public string? RejectReason4 { get; set; }

    public string? App5 { get; set; }

    public string? AppName5 { get; set; }

    public DateTime? AppDate5 { get; set; }

    public string? AppStatus5 { get; set; }

    public string? RejectReason5 { get; set; }

    public string? CustomerRequestType { get; set; }

    public string? CustomerRemark { get; set; }

    public string? TempCustomerRequestType { get; set; }

    public string? TempCustomerRemark { get; set; }

    public string? MarketingName { get; set; }

    public string? BillingName { get; set; }

    public string? TaxsName { get; set; }

    public string? Currency { get; set; }

    public string? ActivityType { get; set; }

    public string? BeneficiaryBankBranch { get; set; }
}

Models/ESSFinance/MDataBank.cs
using System;
using System.Collections.Generic;

namespace CrudIntern.Models.ESSFinance;

public partial class MDataBank
{
    public int Id { get; set; }

    public string? BankName { get; set; }

    public string? BankAddress { get; set; }

    public string? BankCity { get; set; }

    public string? BankCode { get; set; }

    public string? BeneficiaryName { get; set; }

    public string? Nrp { get; set; }

    public string? BeneficiaryAccount { get; set; }

    public string? BeneficiaryCurrency { get; set; }

    public string? Description2 { get; set; }

    public string? BeneficiaryEmailAddress { get; set; }

    public string? TransactionType { get; set; }

    public int? ResidentStatus { get; set; }

    public int? CitizenStatus { get; set; }

    public string? Branch { get; set; }

    public string? Npk { get; set; }

    public string? CustomerReferenceNumber { get; set; }

    public string? EffectiveDate { get; set; }

    public string? SmsNotification { get; set; }

    public string? FaxNotification { get; set; }

    public string? DebitedAccountName { get; set; }

    public string? DebitedAccountNumber { get; set; }

    public string? DebitedAccountCurrency { get; set; }

    public string? ExchangeRate { get; set; }

    public string? TreasuryConfirmationReferenceNumber { get; set; }

    public string? BeneficiaryAddress1 { get; set; }

    public string? BeneficiaryAddress2 { get; set; }

    public string? BeneficiaryAddress3 { get; set; }

    public string? IndonesianMigrantWorkerFlag { get; set; }

    public string? LocationOfReceivingBank { get; set; }

    public string? UnderlyingDocuments { get; set; }

    public int? BeneficiaryType { get; set; }

    public string? TransactionPurposeCode { get; set; }

    public string? EmployeeType { get; set; }

    public string? CostCenter { get; set; }

    public int? DepartmentId { get; set; }
}

Models/ESSFinance/MKmsiBank.cs
using System;
using System.Collections.Generic;

namespace CrudIntern.Models.ESSFinance;

public partial class MKmsiBank
{
    public int Id { get; set; }

    public string? BankName { get; set; }

    public string? Description { get; set; }
}

Models/ESSFinance/MPayTo.cs
using System;
using System.Collections.Generic;

namespace CrudIntern.Models.ESSFinance;

public partial class MPayTo
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? Value { get; set; }

    public string? DepartmentApproval { get; set; }
}

Models/ESSFinance/MPointingActivity.cs
using System;
using System.Collections.Generic;

namespace CrudIntern.Models.ESSFinance;

public partial class MPointingActivity
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? Description { get; set; }
}

Models/ESSFinance/MTarifWht.cs
using System;
using System.Collections.Generic;

namespace CrudIntern.Models.ESSFinance;

public partial class MTarifWht
{
    public int Id { get; set; }

    public decimal? Tarif { get; set; }

    public string? Description { get; set; }
}

Models/ESSFinance/MTypeWht.cs
using System;
using System.Collections.Generic;

namespace CrudIntern.Models.ESSFinance;

public partial class MTypeWht
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? Description { get; set; }
}

Controllers/ESSFinance/MAttnCustomerController.cs
using CrudIntern.Models.ESSFinance;
using CrudIntern.Services;
using Microsoft.AspNetCore.Mvc;

namespace CrudIntern.Controllers.ESSFinance
{
    public class MAttnCustomerController : Controller
    {
        private readonly FinanceDbContext context;

        public MAttnCustomerController(FinanceDbContext context)
        {
            this.context = context;
        }
        public IActionResult Index(string searchTerm)
        {
            ViewData["CurrentFilter"] = searchTerm;
            var AttnCustomer = from c in context.MAttnCustomers
                          select new MAttnCustomer
                          {
                              Id = c.Id,
                              BpCode = c.BpCode ?? "N/A",
                              AttnName = c.AttnName?? "N/A",
                              Email = c.Email ?? "N/A",
                              Description = c.Description ?? "N/A"
                          };
            if (!string.IsNullOrEmpty(searchTerm))
            {
                AttnCustomer = AttnCustomer.Where(b => b.AttnName.Contains(searchTerm));
            }
            return View("~/Views/ESSFinance/MAttnCustomer/Index.cshtml", AttnCustomer.ToList());
        }

        [HttpPost]
        public IActionResult Create(MAttnCustomer newAttnCustomer)
        {
            if (context.MAttnCustomers.Any(b => b.AttnName.ToLower() == newAttnCustomer.AttnName.ToLower()))
            {
                return Json(new { success = false, message = "This AttnCustomer already exists." });
            }
            context.MAttnCustomers.Add(newAttnCustomer);
            context.SaveChanges();

            return Json(new { success = true });
        }

        [HttpPost]
        public IActionResult Edit(MAttnCustomer updatedAttnCustomer)
        {
            var existingAttnCustomer = context.MAttnCustomers.Find(updatedAttnCustomer.Id);

            if (existingAttnCustomer == null)
            {
                return NotFound();
            }
            bool nameExists = context.MAttnCustomers
                .Any(b => b.AttnName.ToLower() == updatedAttnCustomer.AttnName.ToLower() && b.Id != updatedAttnCustomer.Id);

            if (nameExists)
            {
                return Json(new { success = false, message = "This AttnCustomer already exists." });
            }

            existingAttnCustomer.BpCode = updatedAttnCustomer.BpCode ?? existingAttnCustomer.BpCode;
            existingAttnCustomer.AttnName = updatedAttnCustomer.AttnName?? existingAttnCustomer.AttnName;
            existingAttnCustomer.Email = updatedAttnCustomer.Email ?? existingAttnCustomer.Email;
            existingAttnCustomer.Description = updatedAttnCustomer.Description ?? existingAttnCustomer.Description;

            context.SaveChanges();

            return Json(new { success = true });
        }
    }
}

Controllers/ESSFinance/MBankingRoutingCodeController.cs
using CrudIntern.Models.ESSEmployee;
using CrudIntern.Models.ESSFinance;
using CrudIntern.Services;
using Microsoft.AspNetCore.Mvc;

namespace CrudIntern.Controllers.ESSFinance
{
    public class MBankingRoutingCodeController : Controller
    {
        private readonly FinanceDbContext context;

        public MBankingRoutingCodeController(FinanceDbContext context)
        {
            this.context = context;
        }
        public IActionResult Index(string searchTerm)
        {
            ViewData["CurrentFilter"] = searchTerm;
            var BankingRoutingCode = from c in context.MBankingRoutingCodes
                               select new MBankingRoutingCode
                               {
                                   Id = c.Id,
                                   BankName = c.BankName?? "N/A",
                                   RoutingCode = c.RoutingCode ?? "N/A",
                               };
            if (!string.IsNullOrEmpty(searchTerm))
            {
                BankingRoutingCode = BankingRoutingCode.Where(b => b.BankName.Contains(searchTerm));
            }
            return View("~/Views/ESSFinance/MBankingRoutingCode/Index.cshtml", BankingRoutingCode.ToList());
        }

        [HttpPost]
        [HttpPost]
        public IActionResult Create(MBankingRoutingCode newBank)
        {
            if (context.MBankingRoutingCodes.Any(b => b.BankName.ToLower() == newBank.BankName.ToLower()))
            {
                return Json(new { success = false, message = "This bank already exists." });
            }
            context.MBankingRoutingCodes.Add(newBank);
            context.SaveChanges();

            return Json(new { success = true });
        }

        [HttpPost]
        public IActionResult Edit(MBankingRoutingCode updatedBank)
        {
            var existingBank = context.MBankingRoutingCodes.Find(updatedBank.Id);

            if (existingBank == null)
            {
                return NotFound();
            }
            bool nameExists = context.MBankingRoutingCodes
                .Any(b => b.BankName.ToLower() == updatedBank.BankName.ToLower() && b.Id != updatedBank.Id);

            if (nameExists)
            {
                return Json(new { success = false, message = "This bank already exists." });
            }

            existingBank.BankName = updatedBank.BankName ?? existingBank.BankName;
            existingBank.RoutingCode = updatedBank.RoutingCode ?? existingBank.RoutingCode;

            context.SaveChanges();

            return Json(new { success = true });
        }
    }
}

Views/ESSFinance/MAttnCustomer/Index.cshtml
@using CrudIntern.Models.ESSFinance
@model List<MAttnCustomer>
@{
}

<h2 class="text-center mb-5">List AttnCustomer</h2>
<div class="row mb-5">
    <div class="col-md-6">
        <!-- Search Bar -->
        <div class="input-group">
            <input type="text" id="searchAttnCustomer" class="form-control" placeholder="Search by AttnCustomer name...">
            <div class="input-group-append">
                <span class="input-group-text">
                    <i class="fas fa-search"></i>
                </span>
            </div>
        </div>
    </div>
    <div class="col-md-6 text-right">
        <!-- Create Button -->
        <button id="openCreateModal" class="btn btn-success" data-toggle="modal" data-target="#createModal">
            <i class="fas fa-plus"></i> New AttnCustomer
        </button>
    </div>
</div>
<div class="card">
    <div class="card-header">
        <h3 class="card-title">AttnCustomer List</h3>
    </div>
    <div class="card-body">
        @if (ViewData["ErrorMessage"] != null)
        {
            <div class="alert alert-danger">
                @ViewData["ErrorMessage"]
            </div>
        }
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>BpCode</th>
                    <th>AttnName</th>
                    <th>Email</th>
                    <th>Description</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var AttnCustomer in Model)
                {
                    <tr>
                        <td>@AttnCustomer.Id</td>
                        <td>@(AttnCustomer.BpCode ?? "N/A")</td>
                        <td>@(AttnCustomer.AttnName ?? "N/A")</td>
                        <td>@(AttnCustomer.Email ?? "N/A")</td>
                        <td>@(AttnCustomer.Description ?? "N/A")</td>
                        <td>
                            <button class="btn btn-primary btn-sm" onclick="openEditModal('@AttnCustomer.Id', '@(AttnCustomer.BpCode ?? "N/A")', '@(AttnCustomer.AttnName ?? "N/A")', '@(AttnCustomer.Email ?? "N/A")', '@(AttnCustomer.Description ?? "N/A")')">
                                <i class="fas fa-edit"></i> Edit
                            </button>
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>

<!-- Create Modal -->
<div id="createModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Create New AttnCustomer</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="creatMAttnCustomerForm" method="post" asp-controller="MAttnCustomer" asp-action="Create">
                    <div class="form-group">
                        <label for="Name">BpCode</label>
                        <input type="text" class="form-control" id="BpCode" name="BpCode" required />
                    </div>
                    <div class="form-group">
                        <label for="Value">AttnName</label>
                        <input type="text" class="form-control" id="AttnName" name="AttnName" required />
                    </div>
                    <div class="form-group">
                        <label for="Value">Email</label>
                        <input type="email" class="form-control" id="Email" name="Email" required />
                    </div>
                    <div class="form-group">
                        <label for="AttnCustomer">Description</label>
                        <input type="text" class="form-control" id="Description" name="Description" required />
                    </div>
                    <button type="submit" class="btn btn-success">Create</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Edit Modal -->
<div id="editModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit AttnCustomer</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="editErrorAlert" class="alert alert-danger" style="display: none;"></div>

                <form id="editAttnCustomerForm" method="post" asp-controller="MAttnCustomer" asp-action="Edit">
                    <input type="hidden" id="editAttnCustomerId" name="Id" />
                    <div class="form-group">
                        <label for="editName">BpCode</label>
                        <input type="text" class="form-control" id="editBpCode" name="BpCode" required />
                    </div>
                    <div class="form-group">
                        <label for="editValue">AttnCustomer</label>
                        <input type="text" class="form-control" id="editAttnName" name="AttnName" required />
                    </div>
                    <div class="form-group">
                        <label for="editDepartmentId">Email</label>
                        <input type="email" class="form-control" id="editEmail" name="Email" required />
                    </div>

                    <div class="form-group">
                        <label for="editAttnCustomer">Description</label>
                        <input type="text" class="form-control" id="editDescription" name="Description" required />
                    </div>
                    <button type="submit" class="btn btn-success">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- jQuery Validation -->
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<!-- Bootstrap and jQuery -->
<link rel="stylesheet" href="~/css/bootstrap.min.css">
<script src="~/plugins/jquery/jquery.min.js"></script>
<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- SweetAlert -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>

<!-- Custom JavaScript -->
<script>
    function openEditModal(id, BpCode, AttnName, Email, Description) {
        $('#editAttnCustomerId').val(id);
        $('#editBpCode').val(BpCode);
        $('#editAttnName').val(AttnName);
        $('#editEmail').val(Email);
        $('#editCode').val(code);

        $('#editModal').modal('show');
    }

</script>

<script>
    $(document).ready(function () {
        $('#searchAttnCustomer').on('keyup', function () {
            var value = $(this).val().toLowerCase();
            $('.table tbody tr').filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });

    $(document).ready(function () {
        $('#creatMAttnCustomerForm').on('submit', function (event) {
            event.preventDefault();

            $.ajax({
                type: 'POST',
                url: $(this).attr('action'),
                data: $(this).serialize(),
                success: function (response) {
                    if (response.success) {
                        swal("Success!", "AttnCustomer created successfully!", "success").then(() => {
                            $('#createModal').modal('hide');
                            location.reload();
                        });
                    } else {
                        swal("Error!", response.message, "error");
                    }
                },
                error: function (xhr, status, error) {
                    swal("Error!", "An error occurred. Please try again.", "error");
                }
            });
        });

        $('#editAttnCustomerForm').on('submit', function (event) {
            event.preventDefault();

            $.ajax({
                type: 'POST',
                url: $(this).attr('action'),
                data: $(this).serialize(),
                success: function (response) {
                    if (response.success) {
                        swal("Success!", "AttnCustomer updated successfully!", "success").then(() => {
                            $('#editModal').modal('hide');
                            location.reload();
                        });
                    } else {
                        swal("Error!", response.message, "error");
                    }
                },
                error: function (xhr, status, error) {
                    swal("Error!", "An error occurred. Please try again.", "error");
                }
            });
        });
    });
</script>